baseURL = "http://www.thewindowsadmin.com/"
languageCode = "en-us"
title = "The Windows Admin Blog"
theme = "PaperMod"

[params]
  description = "PowerShell • Windows • Sysadmin insights"
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowCodeCopyButtons = true

[params.homeInfoParams]
  Title = "Welcome to The Windows Admin Blog 👋"
  Content = "Practical PowerShell scripts, Windows admin tips, and deep dives into sysadmin work."

[params.assets]
  logo = "/images/Robert-TheWindowsAdmin.png"
  favicon = "/images/Robert-TheWindowsAdmin.png"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3
