baseURL = "/"
languageCode = "en-us"
title = "The Windows Admin Blog"
theme = "PaperMod"

[params]
  assets.logo = "/images/Robert-TheWindowsAdmin.png"
  description = "PowerShell, Windows tips, and sysadmin insights"
